# явно указываем порты, с которых принимать запросы на dhcp и dns
listen-address=127.0.0.1,192.168.10.1,192.168.20.1,192.168.30.1

# указываем интерфейс для которого будет арендовать адреса
interface=eth3.30

# игнорируемые порты
no-dhcp-interface=eth1.10
no-dhcp-interface=eth2.20

# промежуток выдачи адресов: начальный адрес, конечный, маска и время аренды
dhcp-range=192.168.30.100, 192.168.30.200, 255.255.255.0, 12h

# указываем шлюз , а также dns сервер
dhcp-option=option:router,192.168.30.1
dhcp-option=option:dns-server,192.168.30.1

# создаем домен и указваем его как локальный, 
# чтобы при доступе шлюз не искал его в сети интернет по умолчанию
domain=corp.local
local=/corp.local/

# записываем адреса и днс имена для хостов
host-record=gateway.corp.local,192.168.30.1
host-record=web.corp.local,192.168.20.10
host-record=app.corp.local,192.168.20.20
host-record=db.corp.local,192.168.20.30